doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '5.7' # or '8.0', or use 'mariadb' if needed
        url: '%env(resolve:DATABASE_URL)%'
        
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        dql:
            string_functions:
                RAND: DoctrineExtensions\Query\Mysql\Rand
        mappings:
            App:
                is_bundle: false
                type: attribute  # Use attribute for ORM
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
